server:
  port: 0
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: user-service

token:
  expiration_time: 864000000 
  secret: user-service1

gateway:
  ip: 172.18.0.1
